server:
  port: 7200
  servlet:
    context-path: /toolkit
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
  ssl:
    key-store: classpath:tomcat.p12
    key-store-password: casia
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /path/**
  resources:
    static-locations: classpath:/static/
  mail:
    host: smtp.163.com
    # 发送者邮箱账号
    username: 18511085575@163.com
    # 发送者密钥
    password: alarm123456bili
    default-encoding: utf-8
    port: 465   # 端口号465或587
    protocol: smtp
    properties:
      mail:
        debug:
          false
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory


